spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=GMT%2B8&useSSl=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lcl123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
file:
  # 服务器地址
  filePath: /Users/zlatan/Desktop/ceshi1/
  # 前端地址
  urlPath: /Users/zlatan/Desktop/ceshi1/