wx:
  secret: a2cad0b0e025348fc32202c2cd5798e1
spring:
  datasource:
    url: jdbc:mysql://39.97.102.59:3306/oa?serverTimezone=GMT%2B8&useSSl=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oa
    password: YAjGr68MwX

file:
  # 服务器地址
  filePath: /www/wwwroot/oa/files/
  # 前端地址
  urlPath: https://oa.lclong.top/files/
server:
  port: 8081
  ssl:
    protocol: TLS
    key-store: classpath:server.pfx
    key-store-password: 5iNydp8D
    key-store-type: JKS
