spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=GMT%2B8&useSSl=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    cn.lcl.mapper: info
  pattern:
#    console: '%p%m%n'
file:
  # 服务器地址
  filePath: /Users/zlatan/Desktop/ceshi1/
  # 前端地址
  urlPath: /Users/zlatan/Desktop/ceshi1/
url: http://localhost:8000/#/
wx:
  secret: a2cad0b0e025348fc32202c2cd5798e1